site_name: Brytec Docs

site_url: ""
use_directory_urls: false
plugins: []

theme:
  name: readthedocs
  color_mode: dark
  user_color_mode_toggle: true
  titles_only: true
  prev_next_buttons_location: none
  logo: 'images/Brytec Logo.png'

extra_css:
  - 'style/style.css'